//NIM       : 2311500140
//Nama      : Fredy Dwi Saputra
//No. Absen : 7
package View;

import Controller.Controller_Periode;
import java.awt.event.KeyEvent;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Periode
 */
public class FrmPeriode extends javax.swing.JFrame implements java.awt.event.ActionListener, java.awt.event.MouseListener, java.awt.event.KeyListener {
    
    Controller.Controller_Periode controller;
    /**
     * Creates new form frmPeriode
     */
    public FrmPeriode() {
        initComponents();
        txtTA.addActionListener(this);
        cmdTambah.addActionListener(this);
        cmdUbah.addActionListener(this);
        cmdHapus.addActionListener(this);
        cmdBatal.addActionListener(this);
        txtSemester.addActionListener(this);
        
        tblPeriode.addMouseListener(this);
        txtTA.addKeyListener(this);

        setLocationRelativeTo(this);
        controller = new Controller_Periode(this);
        controller.reset();
    }

    public JTable getTblPeriode() {
        return tblPeriode;
    }

    public JTextField getTxtTA() {
        return txtTA;
    }

    public JTextField getTxtSemester() {
        return txtSemester;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblTA = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();
        txtTA = new javax.swing.JTextField();
        txtSemester = new javax.swing.JTextField();
        cmdTambah = new javax.swing.JButton();
        cmdUbah = new javax.swing.JButton();
        cmdHapus = new javax.swing.JButton();
        cmdBatal = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPeriode = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entri Data Matakuliah");

        lblTA.setText("Tahun Ajaran      :");

        lblSemester.setText("Semester             :");

        cmdTambah.setText("Tambah");

        cmdUbah.setText("Ubah");

        cmdHapus.setText("Hapus");

        cmdBatal.setText("Batal");

        tblPeriode.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblPeriode);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTA)
                    .addComponent(lblSemester))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmdBatal)
                        .addGap(318, 318, 318))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtSemester, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdHapus)))
                .addGap(0, 318, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTA)
                    .addComponent(txtTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemester)
                    .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdTambah)
                    .addComponent(cmdUbah)
                    .addComponent(cmdHapus)
                    .addComponent(cmdBatal))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTAActionPerformed

    private void cmdTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTambahActionPerformed
        controller.insert();
        controller.reset();
    }//GEN-LAST:event_cmdTambahActionPerformed

    private void cmdUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUbahActionPerformed
        controller.update();
        controller.reset();
    }//GEN-LAST:event_cmdUbahActionPerformed

    private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusActionPerformed
       controller.delete();
       controller.reset();
    }//GEN-LAST:event_cmdHapusActionPerformed

    private void cmdBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBatalActionPerformed
        controller.reset();
    }//GEN-LAST:event_cmdBatalActionPerformed

    private void txtTAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTAKeyReleased
        controller.isiTabelCari();
    }//GEN-LAST:event_txtTAKeyReleased

    private void txtTAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTAKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(txtTA.getText().isEmpty()){
                controller.reset();
            }
            else{
                controller.isiTabelCari();
                controller.cariData();
                this.txtSemester.requestFocus();
            }
        }
    }//GEN-LAST:event_txtTAKeyPressed

    private void tblPeriodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPeriodeMouseClicked
        controller.isiField(tblPeriode.getSelectedRow());
        this.txtSemester.requestFocus();
    }//GEN-LAST:event_tblPeriodeMouseClicked

    private void txtSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSemesterActionPerformed

    @Override
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        Object source = evt.getSource();
        if (source == txtTA) {
            txtTAActionPerformed(evt);
        } else if (source == cmdTambah) {
            cmdTambahActionPerformed(evt);
        } else if (source == txtSemester) {
            txtSemesterActionPerformed(evt);
        } else if (source == cmdUbah) {
            cmdUbahActionPerformed(evt);
        } else if (source == cmdHapus) {
            cmdHapusActionPerformed(evt);
        } else if (source == cmdBatal) {
            cmdBatalActionPerformed(evt);
        }
    }

    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == tblPeriode) {
            tblPeriodeMouseClicked(evt);
        }
    }
    @Override public void mousePressed(java.awt.event.MouseEvent evt) {}
    @Override public void mouseReleased(java.awt.event.MouseEvent evt) {}
    @Override public void mouseEntered(java.awt.event.MouseEvent evt) {}
    @Override public void mouseExited(java.awt.event.MouseEvent evt) {}

    @Override public void keyTyped(java.awt.event.KeyEvent evt) {}
    @Override
    public void keyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getSource() == txtTA) {
            txtTAKeyPressed(evt);
        }
    }
    @Override
    public void keyReleased(java.awt.event.KeyEvent evt) {
        if (evt.getSource() == txtTA) {
            txtTAKeyReleased(evt);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPeriode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPeriode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPeriode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPeriode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPeriode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBatal;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdTambah;
    private javax.swing.JButton cmdUbah;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblTA;
    private javax.swing.JTable tblPeriode;
    private javax.swing.JTextField txtSemester;
    private javax.swing.JTextField txtTA;
    // End of variables declaration//GEN-END:variables
}
