/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Mahasiswa
 */
public class MenuAkademik extends javax.swing.JFrame {

    /**
     * Creates new form MenuAkademik
     */
    public MenuAkademik() {
        initComponents();
        /* CUSTOM_BINDINGS_START */
        if(mnuPeriode != null) mnuPeriode.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) { mnuPeriodeActionPerformed(evt); } });
        if(mnuKeluar != null) mnuKeluar.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) { mnuKeluarActionPerformed(evt); } });
        if(mnuCetakMatakuliah != null) mnuCetakMatakuliah.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) { mnuCetakMatakuliahActionPerformed(evt); } });
        if(mnuCetakMahasiswa != null) mnuCetakMahasiswa.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) { mnuCetakMahasiswaActionPerformed(evt); } });
        if(mnuCetakKRSS != null) mnuCetakKRSS.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) { mnuCetakKRSSActionPerformed(evt); } });
        if(mnuMahasiswa != null) mnuMahasiswa.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) { mnuMahasiswaActionPerformed(evt); } });
        if(mnuMatakuliah != null) mnuMatakuliah.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) { mnuMatakuliahActionPerformed(evt); } });
        if(mnuTransaksi != null) mnuTransaksi.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) { mnuTransaksiActionPerformed(evt); } });
        if(mnuKRSS != null) mnuKRSS.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) { mnuKRSSActionPerformed(evt); } });
        if(mnuJadwal != null) mnuJadwal.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) { mnuJadwalActionPerformed(evt); } });
        if(mnuSesi != null) mnuSesi.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) { mnuSesiActionPerformed(evt); } });
        if(mnuDosen != null) mnuDosen.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) { mnuDosenActionPerformed(evt); } });
        if(mnuRuang != null) mnuRuang.addActionListener(new java.awt.event.ActionListener() { public void actionPerformed(java.awt.event.ActionEvent evt) { mnuRuangActionPerformed(evt); } });
        if(mnuMatakuliah != null) mnuMatakuliah.addMouseListener(new java.awt.event.MouseAdapter() { public void mouseClicked(java.awt.event.MouseEvent evt) { mnuMatakuliahMouseClicked(evt); } });
        /* CUSTOM_BINDINGS_END */
        setTitle("Sistem Akademik Universitas Budi Luhur");
        setSize(1000, 600);
        setLocationRelativeTo(this);
        Koneksi.Database.KoneksiDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuMahasiswa = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuMatakuliah = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuPeriode = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuKeluar = new javax.swing.JMenuItem();
        mnuTransaksi = new javax.swing.JMenu();
        mnuKRSS = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuCetakMahasiswa = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuCetakMatakuliah = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuCetakKRSS = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuFile.setText("File");

        mnuMahasiswa.setText("Entry Data Mahasiswa");
        mnuMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMahasiswaActionPerformed(evt);
            }
        });
        mnuFile.add(mnuMahasiswa);
        mnuFile.add(jSeparator1);

        mnuMatakuliah.setText("Entry Data Matakuliah");
        mnuMatakuliah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuMatakuliahMouseClicked(evt);
            }
        });
        mnuMatakuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMatakuliahActionPerformed(evt);
            }
        });
        mnuFile.add(mnuMatakuliah);
        mnuFile.add(jSeparator2);

        mnuPeriode.setText("Entry Data Periode");
        mnuPeriode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPeriodeActionPerformed(evt);
            }
        });
        mnuFile.add(mnuPeriode);
        mnuFile.add(jSeparator3);

        mnuSesi = new javax.swing.JMenuItem();
        mnuSesi.setText("Entry Data Sesi");
        mnuSesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSesiActionPerformed(evt);
            }
        });
        mnuFile.add(mnuSesi);
        mnuFile.add(new javax.swing.JPopupMenu.Separator());

        mnuDosen = new javax.swing.JMenuItem();
        mnuDosen.setText("Entry Data Dosen");
        mnuDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDosenActionPerformed(evt);
            }
        });
        mnuFile.add(mnuDosen);
        mnuFile.add(new javax.swing.JPopupMenu.Separator());

        mnuRuang = new javax.swing.JMenuItem();
        mnuRuang.setText("Entry Data Kelas (Ruang)");
        mnuRuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRuangActionPerformed(evt);
            }
        });
        mnuFile.add(mnuRuang);
        mnuFile.add(new javax.swing.JPopupMenu.Separator());

        mnuKeluar.setText("Keluar");
        mnuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKeluarActionPerformed(evt);
            }
        });
        mnuFile.add(mnuKeluar);

        jMenuBar1.add(mnuFile);

        mnuTransaksi.setText("Transaksi");
        mnuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTransaksiActionPerformed(evt);
            }
        });

        mnuKRSS.setText("Entry Data KRSS");
        mnuKRSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKRSSActionPerformed(evt);
            }
        });
        mnuTransaksi.add(mnuKRSS);

        mnuJadwal = new javax.swing.JMenuItem();
        mnuJadwal.setText("Entry Jadwal Matakuliah");
        mnuJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuJadwalActionPerformed(evt);
            }
        });
        mnuTransaksi.add(mnuJadwal);

        mnuKPRS = new javax.swing.JMenuItem();
        mnuKPRS.setText("Entri data KPRS");
        mnuKPRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKPRSActionPerformed(evt);
            }
        });
        mnuTransaksi.add(mnuKPRS);


        jMenuBar1.add(mnuTransaksi);

        jMenu5.setText("Laporan");

        mnuCetakMahasiswa.setText("Cetak Daftar Mahasiswa");
        mnuCetakMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCetakMahasiswaActionPerformed(evt);
            }
        });
        jMenu5.add(mnuCetakMahasiswa);
        jMenu5.add(jSeparator4);

        mnuCetakMatakuliah.setText("Cetak Daftar Matakuliah");
        mnuCetakMatakuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCetakMatakuliahActionPerformed(evt);
            }
        });
        jMenu5.add(mnuCetakMatakuliah);
        jMenu5.add(jSeparator5);

        mnuCetakKRSS.setText("Cetak KRSS");
        mnuCetakKRSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCetakKRSSActionPerformed(evt);
            }
        });
        jMenu5.add(mnuCetakKRSS);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuPeriodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPeriodeActionPerformed
        View.FrmPeriode objMhs = new View.FrmPeriode();
        objMhs.setLocationRelativeTo(this);
        objMhs.setVisible(true);
    }//GEN-LAST:event_mnuPeriodeActionPerformed

    private void mnuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuKeluarActionPerformed

    private void mnuCetakMatakuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCetakMatakuliahActionPerformed
        View.FrmLapRepMtk objMtk = new View.FrmLapRepMtk();
        objMtk.setLocationRelativeTo(this);
        objMtk.setVisible(true);
    }//GEN-LAST:event_mnuCetakMatakuliahActionPerformed

    private void mnuCetakMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {
        View.FrmLapRepMhs objMhs = new View.FrmLapRepMhs();
        objMhs.setLocationRelativeTo(this);
        objMhs.setVisible(true);
    }

    private void mnuCetakKRSSActionPerformed(java.awt.event.ActionEvent evt) {
        View.FrmLapRepKRSS objKRSS = new View.FrmLapRepKRSS();
        objKRSS.setLocationRelativeTo(this);
        objKRSS.setVisible(true);
    }

    private void mnuMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMahasiswaActionPerformed
     View.FrmMahasiswa objMhs = new View.FrmMahasiswa();
     objMhs.setLocationRelativeTo(this);
     objMhs.setVisible(true);
    }//GEN-LAST:event_mnuMahasiswaActionPerformed

    private void mnuMatakuliahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuMatakuliahMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuMatakuliahMouseClicked

    private void mnuMatakuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMatakuliahActionPerformed
    View.FrmMatakuliah objMhs = new View.FrmMatakuliah();
     objMhs.setLocationRelativeTo(this);
     objMhs.setVisible(true);
    }//GEN-LAST:event_mnuMatakuliahActionPerformed

    private void mnuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTransaksiActionPerformed
        
    }//GEN-LAST:event_mnuTransaksiActionPerformed

    private void mnuKRSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKRSSActionPerformed
        View.FrmKRSS objKRSS = new View.FrmKRSS();
        objKRSS.setLocationRelativeTo(this);
        objKRSS.setVisible(true);
    }//GEN-LAST:event_mnuKRSSActionPerformed

    private void mnuJadwalActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            View.FrmJadwal objJadwal = new View.FrmJadwal();
            objJadwal.setLocationRelativeTo(this);
            objJadwal.setVisible(true);
        } catch (Throwable t) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + t.toString());
            t.printStackTrace();
        }
    }

    private void mnuKPRSActionPerformed(java.awt.event.ActionEvent evt) {
        new FrmKPRS().setVisible(true);
    }

    private void mnuSesiActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            View.FrmSesi objSesi = new View.FrmSesi();
            objSesi.setLocationRelativeTo(this);
            objSesi.setVisible(true);
        } catch (Throwable t) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + t.toString());
            t.printStackTrace();
        }
    }

    private void mnuDosenActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            View.FrmDosen objDosen = new View.FrmDosen();
            objDosen.setLocationRelativeTo(this);
            objDosen.setVisible(true);
        } catch (Throwable t) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + t.toString());
            t.printStackTrace();
        }
    }

    private void mnuRuangActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            View.FrmRuang objRuang = new View.FrmRuang();
            objRuang.setLocationRelativeTo(this);
            objRuang.setVisible(true);
        } catch (Throwable t) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + t.toString());
            t.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAkademik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAkademik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAkademik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAkademik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAkademik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem mnuCetakKRSS;
    private javax.swing.JMenuItem mnuCetakMahasiswa;
    private javax.swing.JMenuItem mnuCetakMatakuliah;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuKRSS;
    private javax.swing.JMenuItem mnuKeluar;
    private javax.swing.JMenuItem mnuMahasiswa;
    private javax.swing.JMenuItem mnuMatakuliah;
    private javax.swing.JMenuItem mnuPeriode;
    private javax.swing.JMenu mnuTransaksi;
    private javax.swing.JMenuItem mnuSesi;
    private javax.swing.JMenuItem mnuDosen;
    private javax.swing.JMenuItem mnuRuang;
    private javax.swing.JMenuItem mnuJadwal;
    private javax.swing.JMenuItem mnuKPRS;
    // End of variables declaration//GEN-END:variables
}
